bids/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('system.urls')),
    path('', RedirectView.as_view(url='/system/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

system/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index,  name='index'),
    path('bids/', views.BidListView.as_view(extra_context={'whose': 'all'}), name='bids'),
    path('bid/<int:pk>', views.BidDetailView.as_view(), name='bid-detail'),
    path('mybids/', views.MakingBidsByUserListView.as_view(extra_context={'whose': 'user'}), name='my-bids'),
]

urlpatterns += [
    path('bid/create/', views.bid_create, name='bid-create'),
    path('bid/<int:pk>/update/', views.bid_update, name='bid-update'),
    path('bid/<int:pk>/delete/', views.BidDelete.as_view(), name='bid-delete'),
    path('sticker/', views.sticker_create, name='sticker-create'),
    path('sticker/<int:pk>/update/', views.sticker_update, name='sticker-update'),
    path('sticker/delete<int:pk>', views.StickerDelete.as_view(), name='sticker-delete'),
    path('bid/search/', views.bid_search, name='bid-search'),
    path('bid/archive/', views.BidArchiveView.as_view(extra_context={'whose': 'past'}), name='bid-archive'),
    ]

system/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Bid(models.Model):

    text = models.TextField(max_length=1000, help_text="Enter a brief description of the bid", verbose_name="Текст заявки")

    TYPE_OF_BID = (
        ('h', 'Железо'),
        ('c', 'Картридж'),
        ('pr', 'Принтер'),
        ('w', 'Сеть'),
        ('t', 'Телефон'),
        ('v', 'Вирусы'),
        ('s', 'Софт'),
        ('pa', 'Парус'),
        ('br', 'Бюрократия'),
    )

    type_bid = models.CharField(max_length=2, choices=TYPE_OF_BID, blank=True, default='h', verbose_name="Тип заявки")
    location = models.CharField(max_length=200, default='Кабинет', verbose_name="Кабинет")
    # location = models.ForeignKey('Location', on_delete=models.SET_NULL, null=True)
    telephone_num = models.CharField(max_length=200, default='Телефон', verbose_name="Телефон")
    # telephone_num = models.ForeignKey('Telephone', on_delete=models.SET_NULL, null=True)
    bider = models.CharField(max_length=200, default='', verbose_name="Заявитель")
    # bider = models.ForeignKey('Bider', on_delete=models.SET_NULL, null=True)
    maker = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Исполнитель")
    creator = models.CharField(max_length=200, default='', verbose_name="Принял заявку")
    helper = models.CharField(max_length=200, null=True, verbose_name="Помощник")
    # helper = models.ManyToManyField('Helper')
    time_creation = models.DateTimeField(null=True, verbose_name="Дата создания заявки")
    time_start = models.DateTimeField(null=True, verbose_name="Дата начала работы")
    time_done = models.DateTimeField(null=True, verbose_name="Дата завершения работы")

    STATUS = (
        ('a', 'Принята'),
        ('w', 'В работе'),
        ('f', 'Выполнена'),
    )

    status = models.CharField(max_length=1, choices=STATUS, default='a', verbose_name="Статус заявки")
    comment = models.CharField(max_length=200, default='', verbose_name="Комментарий")
    result = models.CharField(max_length=300, default='', verbose_name="Результат работы")

    class Meta:
      #   ordering = ["time_creation"]
        verbose_name_plural = "Заявки"
        verbose_name = "Заявка"

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('bid-detail', args=[str(self.id)])


class Sticker(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название", null=True)
    text = models.CharField(max_length=500, verbose_name="Текст объявления")
    date_creation = models.DateTimeField(null=True, verbose_name="Дата создания")


    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = "Объявления"
        verbose_name = "Объявление"

system/views.py
from django.shortcuts import render
from .models import Bid, Sticker
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from .filters import BidListFilter, BidArchiveFilter, BidUserFilter
from django_filters import rest_framework as filters


# Create your views here.

def index(request):
    num_bids=Bid.objects.all().count()
    num_bids_a=Bid.objects.all().filter(status='a').count()
    num_bids_w=Bid.objects.all().filter(status='w').count()
    num_bids_f=Bid.objects.all().filter(status='f').count()

    all_stickers = Sticker.objects.all()

    if request.user.is_authenticated:
        if request.user.has_perm('system.delete_bid'):
            all_users = list()
            for user in User.objects.all():
                user_num_bids_a=Bid.objects.filter(maker=user).filter(status='a').count()
                user_num_bids_w=Bid.objects.filter(maker=user).filter(status='w').count()
                user_num_bids_f=Bid.objects.filter(maker=user).filter(status='f').count()
                user_num_bids=user_num_bids_a+user_num_bids_w+user_num_bids_f
                all_users.append((user.get_username(), user_num_bids, user_num_bids_a, user_num_bids_w, user_num_bids_f,))

            return render(
                        request,
                        'index.html',
                        context={'num_bids': num_bids,
                                 'num_bids_a': num_bids_a,
                                 'num_bids_w': num_bids_w,
                                 'num_bids_f': num_bids_f,
                                 'all_stickers': all_stickers,
                                 'all_users': all_users},
    )

        user_num_bids_a=Bid.objects.filter(maker=request.user).filter(status='a').count()
        user_num_bids_w=Bid.objects.filter(maker=request.user).filter(status='w').count()
        user_num_bids_f=Bid.objects.filter(maker=request.user).filter(status='f').count()
        user_num_bids=user_num_bids_a+user_num_bids_w+user_num_bids_f

        return render(
                        request,
                        'index.html',
                        context={'num_bids': num_bids,
                                 'num_bids_a': num_bids_a,
                                 'num_bids_w': num_bids_w,
                                 'num_bids_f': num_bids_f,
                                 'all_stickers': all_stickers,
                                 'user_num_bids': user_num_bids,
                                 'user_num_bids_a': user_num_bids_a,
                                 'user_num_bids_w': user_num_bids_w,
                                 'user_num_bids_f': user_num_bids_f},
    )

    return render(
        request,
        'index.html',
        context={'num_bids': num_bids,
                 'num_bids_a': num_bids_a,
                 'num_bids_w': num_bids_w,
                 'num_bids_f': num_bids_f,
                 'all_stickers': all_stickers},
    )


class BidListView(generic.ListView):
    model = Bid
    paginate_by = 25
    queryset = Bid.objects.all().exclude(status="f").order_by('-time_creation')
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = BidListFilter
    # def get_queryset(self):
    #     return Bid.objects.all().exclude(status="f").order_by('-time_creation')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = BidListFilter(self.request.GET, queryset=self.get_queryset())
        return context


class BidArchiveView(generic.ListView):
    queryset = Bid.objects.all().filter(status="f").order_by('-time_creation')

    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = BidArchiveFilter
    model = Bid
    template_name = 'system/bids_list.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = BidArchiveFilter(self.request.GET, queryset=self.get_queryset())
        return context


class BidDetailView(generic.DetailView):
    model = Bid


class MakingBidsByUserListView(LoginRequiredMixin,generic.ListView):
    model = Bid
    template_name = 'system/bids_list.html'
    paginate_by = 10
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = BidUserFilter

    def get_queryset(self):
        return Bid.objects.all().exclude(status="f").filter(maker=self.request.user).order_by('-time_creation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = BidUserFilter(self.request.GET, queryset=self.get_queryset())
        return context




class BidDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Bid
    success_url = reverse_lazy('bids')

    permission_required = ('system.delete_bid')



from system.forms import CreateBidForm


@login_required
def bid_create(request):
    """View function for renewing a specific BookInstance by librarian."""
    # book_instance = get_object_or_404(BookInstance, pk=pk)
    bid = Bid()

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateBidForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)

            bid.text = form.cleaned_data['text']
            bid.type_bid = form.cleaned_data['type_bid']
            bid.location = form.cleaned_data['location']
            bid.telephone_num = form.cleaned_data['telephone_num']
            bid.bider = form.cleaned_data['bider']
            bid.maker = form.cleaned_data['maker']

            bid.creator = request.user.get_username()

            bid.helper = form.cleaned_data['helper']
            bid.status = form.cleaned_data['status']
            bid.result = form.cleaned_data['result']
            bid.comment = form.cleaned_data['comment']

            if bid.status == "w" and bid.time_creation is None:
                bid.time_start = datetime.datetime.today()
                bid.time_creation = datetime.datetime.today()
            elif bid.status == "w":
                bid.time_start = datetime.datetime.today()
            elif bid.status == "a":
                bid.time_creation = datetime.datetime.today()
            elif bid.status == "f" and bid.time_creation is None and bid.time_start is None:
                bid.time_start = datetime.datetime.today()
                bid.time_creation = datetime.datetime.today()
                bid.time_done = datetime.datetime.today()
            elif bid.status == "f" and bid.time_start is None:
                bid.time_start = datetime.datetime.today()
                bid.time_done = datetime.datetime.today()

            bid.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('bid-detail', args=(bid.pk,)))

    # If this is a GET (or any other method) create the default form
    else:
        proposed_text = " "
        form = CreateBidForm(initial={'text': proposed_text})

    context = {
        'form': form,
        'bid-detail': bid,
    }

    return render(request, 'system/bid_create.html', context)


@login_required
def bid_update(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    bid = get_object_or_404(Bid, pk=pk)
    # bid = Bid()

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateBidForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)

            bid.text = form.cleaned_data['text']
            bid.type_bid = form.cleaned_data['type_bid']
            bid.location = form.cleaned_data['location']
            bid.telephone_num = form.cleaned_data['telephone_num']
            bid.bider = form.cleaned_data['bider']
            bid.maker = form.cleaned_data['maker']
            bid.helper = form.cleaned_data['helper']
            # bid.status = form.cleaned_data['status']
            bid.result = form.cleaned_data['result']
            bid.comment = form.cleaned_data['comment']
            if bid.status != form.cleaned_data['status']:
                bid.status = form.cleaned_data['status']
                if bid.status == "w":
                    bid.time_start = datetime.datetime.today()
                elif bid.status == "f":
                # bid.time_start = datetime.datetime.today()
                    bid.time_done = datetime.datetime.today()
            bid.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('bid-detail', args=(bid.pk,)))

    # If this is a GET (or any other method) create the default form
    else:

        form = CreateBidForm(initial={
            'text': bid.text,
            'type_bid': bid.type_bid,

system/templates/system/bid_archive.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список заявок</h1>


    {% if bid_list %}

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for bid.." title="Type in a name">

<table class="table table-striped" id="myTable">
   <tr class="header"><th>Номер заявки</th>
       <th>Тип</th>
       <th>Содержание</th>
       <th>Место</th>
       <th>Телефон</th>
       <th>Заявитель</th>
       <th>Исполнитель</th>
       <th>Время поступления</th>
       <th>Начало работы</th>
       <th>Завершение работы</th>
       <th>Состояние</th>
   </tr>
    {% for bid in bid_list %}
   <tr>
       <td><a href="{{ bid.get_absolute_url }}">{{ bid.id }}</a></td>
       <td>{{ bid.get_type_bid_display }}</td>
       <td>{{ bid.text }}</td>
       <td>{{ bid.location }}</td>
       <td>{{ bid.telephone_num }}</td>
       <td>{{ bid.bider }}</td>
       <td>{{ bid.maker }}</td>
       <td>{{ bid.time_creation|date:"d.m.Y H:i" }}</td>
       <td>{{ bid.time_start|date:"d.m.Y H:i" }}</td>
       <td>{{ bid.time_done|date:"d.m.Y H:i" }}</td>
       <td>
           {% if bid.status == "a" %}<span class="badge bg-primary">Принята</span>
           {% endif %}

           {% if bid.status == "w" %}<span class="badge bg-danger">В работе</span>
           {% endif %}

           {% if bid.status == "f" %}<span class="badge bg-success">Выполнено</span>
           {% endif %}

       </td>
   </tr>
    {% endfor %}
</table>


    {% else %}
      <p>Заявок нет.</p>
    {% endif %}


<script language="javascript" type="text/javascript">
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

system/templates/system/bid_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удалить заявку</h1>

<p>Вы точно хотите удалить заявку?: {{ bid }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Удалить" />
  <input type="button" value="Нет" onClick="location.href='{% url "bid-detail" bid.pk %}'">
</form>

{% endblock %}

system/templates/system/bid_create.html
{% extends "base_generic.html" %}

{% block content %}

<div class="col-12 col-sm-9 col-md-9 col-lg-5">
    <form action="" method="post">
        {% csrf_token %}
        <table class="table">
        {{ form.as_table }}
        </table>
        <input type="submit" value="Создать" />
        <input type="reset" value="Очистить" />
    </form>
</div>

{% endblock %}

system/templates/system/bid_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
<div class="col-12 col-sm-9 col-md-9 col-lg-5">
   <div class="row"><h1>Заявка №:{{ bid.id }}</h1></div>
   <div class="row">
       <div class="col-4 bg-light p-3 border"><strong>Тип:</strong></div>
        <!--('h', 'hard')
        ('c', 'cartridge')
        ('pr', 'printer')
        ('w', 'web or net')
        ('t', 'telephone')
        ('v', 'viruses')
        ('s', 'soft')
        ('pa', 'Parus')-->
       <div class="col-8 bg-light p-3 border">

      {{ bid.get_type_bid_display }}

      {% if bid.type_bid == "h" %}{% load django_bootstrap_icons %}<i class="bi bi-tools"></i>
      {% endif %}

      {% if bid.type_bid == "c" %}{% load django_bootstrap_icons %}{% bs_icon 'palette' %}
      {% endif %}

      {% if bid.type_bid == "pr" %}{% load django_bootstrap_icons %}{% bs_icon 'printer' %}
      {% endif %}

      {% if bid.type_bid == "w" %}{% load django_bootstrap_icons %}{% bs_icon 'globe' %}
      {% endif %}

      {% if bid.type_bid == "t" %}{% load django_bootstrap_icons %}<i class="bi bi-telephone-inbound-fill"></i>
      {% endif %}

      {% if bid.type_bid == "v" %}{% load django_bootstrap_icons %}<i class="bi bi-exclamation-triangle"></i>
      {% endif %}

      {% if bid.type_bid == "s" %}{% load django_bootstrap_icons %}{% bs_icon 'bug' %}
      {% endif %}

      {% if bid.type_bid == "pa" %}{% load django_bootstrap_icons %}{% bs_icon 'alarm' %}
      {% endif %}

      {% if bid.type_bid == "br" %}{% load django_bootstrap_icons %}{% bs_icon 'emoji-angry' %}
      {% endif %}
       </div>
  </div>

  <div class="row"><div class="col-4 bg-light p-3 border"><strong>Содержание:</strong></div> <div class="col-8 bg-light p-3 border">{{ bid.text|safe|linebreaks }}</div></div>
  <div class="row"><div class="col-4 bg-light p-3 border"><strong>Место:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.location }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Номер телефона:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.telephone_num }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Заявитель:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.bider }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Заявку принял:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.creator }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Исполнитель:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.maker }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Ассистент:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.helper }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Время поступления:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.time_creation|date:" d.m.Y  H:i l " }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Начало работы:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.time_start|date:"d.m.Y H:i l" }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Завершение работы:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.time_done|date:"d.m.Y  H:i  l" }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Состояние:</strong></div><div class="col-8 bg-light p-2 border">
  <h4>{% if bid.status == "a" %}<span class="badge bg-primary">Принята</span>
           {% endif %}

           {% if bid.status == "w" %}<span class="badge bg-danger">В работе</span>
           {% endif %}

           {% if bid.status == "f" %}<span class="badge bg-success">Выполнено</span>
      {% endif %}</h4>
    </div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Комментарий:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.comment }}</div></div>
    <div class="row"><div class="col-4 bg-light p-3 border"><strong>Результат:</strong></div><div class="col-8 bg-light p-3 border"> {{ bid.result }}</div></div>

<div class="row">


<p></p>
        <input type="button" value="Редактировать заявку" onClick="location.href='{% url "bid-update" bid.pk %}'">

    {% if perms.system.delete_bid %}

         <input type="button" value="Удалить заявку" onClick="location.href='{% url "bid-delete" bid.pk %}'">


    {% endif %}

</div>
</div>
</div>
{% endblock %}

system/templates/system/bid_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Принять" />
    <input type="reset" value="Очистить">


</form>
{% endblock %}

system/templates/system/bid_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if whose == 'all' %}
    <h1>Список заявок</h1>
{% elif whose == 'user' %}
    <h1>Мои заявки</h1>
{% elif whose == 'past' %}
    <h1>Завершенные заявки</h1>
{% endif %}

{% if bid_list %}
<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Поиск по содержанию.." title="Type in a name">

<p></p>

<div class="table-responsive-xxl">
<table class="table table-striped table-bordered" id="myTable">
   <tr class="header"><th>Номер заявки</th>
       <th>Тип</th>
       <th>Содержание</th>
       <th>Место</th>
       <th>Телефон</th>
       <th>Заявитель</th>
       <th>Исполнитель</th>
       <th>Время поступления</th>
       <th>Начало работы</th>
       <th>Завершение работы</th>
       <th>Состояние</th>
   </tr>
    {% for bid in bid_list %}
   <tr>
       <td><a href="{{ bid.get_absolute_url }}">{{ bid.id }}</a></td>
       <td>{{ bid.get_type_bid_display }}</td>
       <td>{{ bid.text }}</td>
       <td>{{ bid.location }}</td>
       <td>{{ bid.telephone_num }}</td>
       <td>{{ bid.bider }}</td>
       <td>{{ bid.maker }}</td>
       <td>{{ bid.time_creation|date:"d.m.Y H:i" }}</td>
       <td>{{ bid.time_start|date:"d.m.Y H:i" }}</td>
       <td>{{ bid.time_done|date:"d.m.Y H:i" }}</td>
       <td>

           {% if bid.status == "a" %}<h4><span class="badge bg-primary">Принята
           <a class="btn btn-secondary btn-sm" href='{% url "bid-update" bid.pk %}' role="button"><i class="bi bi-pencil"></i></a></span></h4>
           {% endif %}

           {% if bid.status == "w" %}<h4><span class="badge bg-danger">В работе
           <a class="btn btn-secondary btn-sm" href='{% url "bid-update" bid.pk %}' role="button"><i class="bi bi-pencil"></i></a></span></h4>
           {% endif %}

           {% if bid.status == "f" %}<h4><span class="badge bg-success">Выполнено
           <a class="btn btn-secondary btn-sm" href='{% url "bid-update" bid.pk %}' role="button"><i class="bi bi-pencil"></i></a></span></h4>
           {% endif %}

       </td>
   </tr>
    {% endfor %}
</table>
</div>

    {% else %}
      <p>Заявок нет.</p>
    {% endif %}


<script language="javascript" type="text/javascript">
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

system/templates/system/bids_for_user.html
{% extends "base_generic.html" %}


{% block content %}
    <h1>Мои заявки</h1>

{% if bid_list %}

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Поиск по содержанию.." title="Type in a name">

<table class="table table-striped" id="myTable">
   <tr class="header"><th>Номер заявки</th>
       <th>Тип</th>
       <th>Содержание</th>
       <th>Место</th>
       <th>Телефон</th>
       <th>Заявитель</th>
       <th>Исполнитель</th>
       <th>Время поступления</th>
       <th>Начало работы</th>
       <th>Завершение работы</th>
       <th>Состояние</th>
   </tr>
    {% for bid in bid_list %}
   <tr>
       <td><a href="{{ bid.get_absolute_url }}">{{ bid.id }}</a></td>
       <td>{{ bid.get_type_bid_display }}</td>
       <td>{{ bid.text }}</td>
       <td>{{ bid.location }}</td>
       <td>{{ bid.telephone_num }}</td>
       <td>{{ bid.bider }}</td>
       <td>{{ bid.maker }}</td>
       <td>{{ bid.time_creation|date:"d.m.Y H:i" }}</td>
       <td>{{ bid.time_start|date:"d.m.Y H:i" }}</td>
       <td>{{ bid.time_done|date:"d.m.Y H:i" }}</td>
       <td>
           {% if bid.status == "a" %}<span class="badge bg-primary">Принята</span>
           {% endif %}

           {% if bid.status == "w" %}<span class="badge bg-danger">В работе</span>
           {% endif %}

           {% if bid.status == "f" %}<span class="badge bg-success">Выполнено</span>
           {% endif %}

       </td>
   </tr>
    {% endfor %}
</table>

{% else %}
      <p>Для вас нет заявок.</p>
{% endif %}

<script language="javascript" type="text/javascript">
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

{% endblock %}

system/templates/system/sticker_update.html
{% extends "base_generic.html" %}

{% block content %}

<div class="col-12 col-sm-9 col-md-9 col-lg-5">
<h1>Стикер №:{{ sticker.id }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            <label for="{{ form.name.id_for_label }}">Название:</label>
            <br>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.text.id_for_label }}">Содержание:</label>
            <br>
            {{ form.text }}
            {{ form.text.errors }}
        </div>
        <input type="submit" value="Сохранить" />
        <input type="reset" value="Очистить" />
    </form>
    <p></p>
    {% if perms.system.delete_sticker %}

    <input type="button" value="Удалить" onClick="location.href='{% url "sticker-delete" sticker.pk %}'">
    {% endif %}
</div>

{% endblock %}